/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_johannes_curses_Curses */

#ifndef _Included_de_johannes_curses_Curses
#define _Included_de_johannes_curses_Curses
#ifdef __cplusplus
extern "C" {
#endif
#undef de_johannes_curses_Curses_BLACK
#define de_johannes_curses_Curses_BLACK 1L
#undef de_johannes_curses_Curses_DARK_GRAY
#define de_johannes_curses_Curses_DARK_GRAY 2L
#undef de_johannes_curses_Curses_LIGHT_GRAY
#define de_johannes_curses_Curses_LIGHT_GRAY 3L
#undef de_johannes_curses_Curses_WHITE
#define de_johannes_curses_Curses_WHITE 4L
#undef de_johannes_curses_Curses_DARK_RED
#define de_johannes_curses_Curses_DARK_RED 5L
#undef de_johannes_curses_Curses_LIGHT_RED
#define de_johannes_curses_Curses_LIGHT_RED 6L
#undef de_johannes_curses_Curses_DARK_GREEN
#define de_johannes_curses_Curses_DARK_GREEN 7L
#undef de_johannes_curses_Curses_LIGHT_GREEN
#define de_johannes_curses_Curses_LIGHT_GREEN 8L
#undef de_johannes_curses_Curses_DARK_BLUE
#define de_johannes_curses_Curses_DARK_BLUE 9L
#undef de_johannes_curses_Curses_LIGHT_BLUE
#define de_johannes_curses_Curses_LIGHT_BLUE 10L
#undef de_johannes_curses_Curses_DARK_CYAN
#define de_johannes_curses_Curses_DARK_CYAN 11L
#undef de_johannes_curses_Curses_LIGHT_CYAN
#define de_johannes_curses_Curses_LIGHT_CYAN 12L
#undef de_johannes_curses_Curses_DARK_MAGENTA
#define de_johannes_curses_Curses_DARK_MAGENTA 13L
#undef de_johannes_curses_Curses_LIGHT_MAGENTA
#define de_johannes_curses_Curses_LIGHT_MAGENTA 14L
#undef de_johannes_curses_Curses_DARK_YELLOW
#define de_johannes_curses_Curses_DARK_YELLOW 15L
#undef de_johannes_curses_Curses_LIGHT_YELLOW
#define de_johannes_curses_Curses_LIGHT_YELLOW 16L
#undef de_johannes_curses_Curses_CORNER_UPPER_LEFT
#define de_johannes_curses_Curses_CORNER_UPPER_LEFT 9484L
#undef de_johannes_curses_Curses_CORNER_UPPER_RIGHT
#define de_johannes_curses_Curses_CORNER_UPPER_RIGHT 9488L
#undef de_johannes_curses_Curses_CORNER_LOWER_LEFT
#define de_johannes_curses_Curses_CORNER_LOWER_LEFT 9492L
#undef de_johannes_curses_Curses_CORNER_LOWER_RIGHT
#define de_johannes_curses_Curses_CORNER_LOWER_RIGHT 9496L
#undef de_johannes_curses_Curses_CORNER_ROUNDED_UPPER_LEFT
#define de_johannes_curses_Curses_CORNER_ROUNDED_UPPER_LEFT 9581L
#undef de_johannes_curses_Curses_CORNER_ROUNDED_UPPER_RIGHT
#define de_johannes_curses_Curses_CORNER_ROUNDED_UPPER_RIGHT 9582L
#undef de_johannes_curses_Curses_CORNER_ROUNDED_LOWER_LEFT
#define de_johannes_curses_Curses_CORNER_ROUNDED_LOWER_LEFT 9584L
#undef de_johannes_curses_Curses_CORNER_ROUNDED_LOWER_RIGHT
#define de_johannes_curses_Curses_CORNER_ROUNDED_LOWER_RIGHT 9583L
#undef de_johannes_curses_Curses_TEE_DOWN_POINTING
#define de_johannes_curses_Curses_TEE_DOWN_POINTING 9516L
#undef de_johannes_curses_Curses_TEE_UP_POINTING
#define de_johannes_curses_Curses_TEE_UP_POINTING 9524L
#undef de_johannes_curses_Curses_TEE_RIGHT_POINTING
#define de_johannes_curses_Curses_TEE_RIGHT_POINTING 9500L
#undef de_johannes_curses_Curses_TEE_LEFT_POINTING
#define de_johannes_curses_Curses_TEE_LEFT_POINTING 9508L
#undef de_johannes_curses_Curses_CROSS
#define de_johannes_curses_Curses_CROSS 9532L
#undef de_johannes_curses_Curses_LINE_HORIZONTAL
#define de_johannes_curses_Curses_LINE_HORIZONTAL 9472L
#undef de_johannes_curses_Curses_LINE_VERTICAL
#define de_johannes_curses_Curses_LINE_VERTICAL 9474L
#undef de_johannes_curses_Curses_ATTRIB_REVERSE
#define de_johannes_curses_Curses_ATTRIB_REVERSE 0L
#undef de_johannes_curses_Curses_ATTRIB_DIM
#define de_johannes_curses_Curses_ATTRIB_DIM 1L
#undef de_johannes_curses_Curses_ATTRIB_ITALIC
#define de_johannes_curses_Curses_ATTRIB_ITALIC 2L
#undef de_johannes_curses_Curses_ATTRIB_INVIS
#define de_johannes_curses_Curses_ATTRIB_INVIS 3L
#undef de_johannes_curses_Curses_ATTRIB_BLINK
#define de_johannes_curses_Curses_ATTRIB_BLINK 4L
#undef de_johannes_curses_Curses_ATTRIB_UNDERLINE
#define de_johannes_curses_Curses_ATTRIB_UNDERLINE 5L
/*
 * Class:     de_johannes_curses_Curses
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_init
  (JNIEnv *, jobject);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_destroy
  (JNIEnv *, jobject);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    cls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_cls
  (JNIEnv *, jobject);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    setCursor
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_setCursor
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    moveCursor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_moveCursor
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_setColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    defineColor
 * Signature: (IFFF)I
 */
JNIEXPORT jint JNICALL Java_de_johannes_curses_Curses_defineColor
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    defineColorPair
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_de_johannes_curses_Curses_defineColorPair
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    print
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_print
  (JNIEnv *, jobject, jchar);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    printstr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_printstr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    getch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_johannes_curses_Curses_getch
  (JNIEnv *, jobject);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    getMouseEvent
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_de_johannes_curses_Curses_getMouseEvent
  (JNIEnv *, jobject);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    inch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_johannes_curses_Curses_inch
  (JNIEnv *, jobject);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    moveinch
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_johannes_curses_Curses_moveinch
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    attron
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_attron
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    attroff
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_attroff
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_johannes_curses_Curses_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_johannes_curses_Curses_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    drawBox
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_drawBox
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    drawHorizontalLine
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_drawHorizontalLine
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    drawVerticalLine
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_drawVerticalLine
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    drawCorner
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_drawCorner
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    drawTee
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_drawTee
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    drawArrow
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_drawArrow
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     de_johannes_curses_Curses
 * Method:    refresh
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_johannes_curses_Curses_refresh
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
